In [1]:
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt
import cv2

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
fashion_mnist = keras.datasets.fashion_mnist
(train_images, train_labels),(test_images, test_labels)= fashion_mnist.load_data()

In [3]:
print(f"training images: {len(train_images)}")
print(f"training labels: {len(test_images)}")

training images: 60000
training labels: 10000


## KNN Classifier

- training set: 3000
- test set: 1000

In [4]:
x_train = train_images[: 3000]
y_train = train_labels[: 3000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]

In [5]:
# reshape: 3D -> 2D
def reshape(dataset): 
    num, x_value, y_value = dataset.shape
    dataset = dataset.reshape((num, x_value * y_value))
    return dataset
x_train = reshape(x_train)
x_test = reshape(x_test)

In [6]:
# fit classifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [7]:
# predict
predict_y = knn.predict(x_test)

In [8]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.806
precision score:  0.8174333849677498
recall score:  0.8083572787387018
f1 score:  0.8102244121587207


In [9]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.71      0.82      0.76       107
           1       0.92      0.96      0.94       105
           2       0.64      0.68      0.66       111
           3       0.86      0.74      0.80        93
           4       0.76      0.70      0.73       115
           5       0.97      0.77      0.86        87
           6       0.59      0.59      0.59        97
           7       0.85      0.93      0.89        95
           8       0.99      0.93      0.96        95
           9       0.88      0.96      0.91        95

    accuracy                           0.81      1000
   macro avg       0.82      0.81      0.81      1000
weighted avg       0.81      0.81      0.81      1000



In [10]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[ 88   3   5   2   0   0   9   0   0   0]
 [  2 101   0   2   0   0   0   0   0   0]
 [  6   1  76   0  14   0  14   0   0   0]
 [ 10   4   1  69   4   0   5   0   0   0]
 [  1   1  17   5  81   0  10   0   0   0]
 [  0   0   1   0   0  67   0  11   1   7]
 [ 16   0  14   2   8   0  57   0   0   0]
 [  0   0   0   0   0   1   0  88   0   6]
 [  1   0   4   0   0   1   1   0  88   0]
 [  0   0   0   0   0   0   0   4   0  91]]


## KNN Classifier
- training set: 6000
- test set: 1000

In [11]:
x_train = train_images[: 6000]
y_train = train_labels[: 6000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]
x_train = reshape(x_train)
x_test = reshape(x_test)

In [12]:
# fit classifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)
# predict
predict_y = knn.predict(x_test)

In [13]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.816
precision score:  0.8261289198532291
recall score:  0.8173032626211448
f1 score:  0.8186216959401345


In [14]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.69      0.83      0.75       107
           1       0.95      0.96      0.96       105
           2       0.69      0.80      0.74       111
           3       0.87      0.77      0.82        93
           4       0.80      0.70      0.75       115
           5       0.97      0.80      0.88        87
           6       0.58      0.52      0.55        97
           7       0.88      0.91      0.89        95
           8       0.98      0.92      0.95        95
           9       0.85      0.96      0.90        95

    accuracy                           0.82      1000
   macro avg       0.83      0.82      0.82      1000
weighted avg       0.82      0.82      0.82      1000



In [15]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[ 89   2   3   2   0   0  10   0   1   0]
 [  1 101   0   2   1   0   0   0   0   0]
 [  5   0  89   1   7   0   9   0   0   0]
 [ 11   2   2  72   2   0   4   0   0   0]
 [  1   1  17   4  81   0  11   0   0   0]
 [  0   0   0   0   0  70   0   8   1   8]
 [ 19   0  16   2  10   0  50   0   0   0]
 [  0   0   0   0   0   1   0  86   0   8]
 [  3   0   2   0   0   1   2   0  87   0]
 [  0   0   0   0   0   0   0   4   0  91]]


## KNN Classifier
- training set: 12000
- test set: 1000

In [16]:
x_train = train_images[: 12000]
y_train = train_labels[: 12000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]
x_train = reshape(x_train)
x_test = reshape(x_test)

In [17]:
# fit classifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train, y_train)
# predict
predict_y = knn.predict(x_test)

In [18]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.812
precision score:  0.823805187188495
recall score:  0.813877009165226
f1 score:  0.8155680152573896


In [19]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.67      0.82      0.74       107
           1       0.99      0.96      0.98       105
           2       0.69      0.80      0.74       111
           3       0.84      0.76      0.80        93
           4       0.79      0.67      0.72       115
           5       0.97      0.80      0.88        87
           6       0.59      0.54      0.56        97
           7       0.86      0.91      0.88        95
           8       0.99      0.92      0.95        95
           9       0.86      0.96      0.91        95

    accuracy                           0.81      1000
   macro avg       0.82      0.81      0.82      1000
weighted avg       0.82      0.81      0.81      1000



In [20]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[ 88   0   5   3   0   0  10   0   1   0]
 [  2 101   0   2   0   0   0   0   0   0]
 [  6   0  89   1   7   0   8   0   0   0]
 [ 13   1   2  71   4   0   2   0   0   0]
 [  1   0  18   6  77   0  13   0   0   0]
 [  0   0   0   0   0  70   0  10   0   7]
 [ 19   0  14   2  10   0  52   0   0   0]
 [  0   0   0   0   0   1   0  86   0   8]
 [  3   0   1   0   0   1   3   0  87   0]
 [  0   0   0   0   0   0   0   4   0  91]]


## DT Classifier
- training set: 3000
- test set: 1000

In [21]:
x_train = train_images[: 3000]
y_train = train_labels[: 3000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]
x_train = reshape(x_train)
x_test = reshape(x_test)

In [22]:
# fit data
DT = DecisionTreeClassifier()
DT.fit(x_train, y_train)
# predict
predict_y = DT.predict(x_test)

In [23]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.703
precision score:  0.7063045474456715
recall score:  0.7085655807741871
f1 score:  0.7071533142230422


In [24]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.68      0.65      0.67       107
           1       0.86      0.91      0.88       105
           2       0.59      0.57      0.58       111
           3       0.67      0.65      0.66        93
           4       0.55      0.54      0.55       115
           5       0.83      0.82      0.82        87
           6       0.40      0.41      0.41        97
           7       0.81      0.85      0.83        95
           8       0.81      0.84      0.82        95
           9       0.87      0.84      0.86        95

    accuracy                           0.70      1000
   macro avg       0.71      0.71      0.71      1000
weighted avg       0.70      0.70      0.70      1000



In [25]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[70  4  4  3  2  1 21  0  2  0]
 [ 1 96  1  5  1  1  0  0  0  0]
 [ 6  0 63  4 24  0 11  0  3  0]
 [ 6  8  1 60  5  1  9  0  3  0]
 [ 2  2 22  6 62  0 15  0  6  0]
 [ 0  1  0  1  0 71  0 11  1  2]
 [17  0 12  7 17  0 40  0  4  0]
 [ 0  0  0  0  0  5  0 81  0  9]
 [ 1  1  3  2  1  2  3  1 80  1]
 [ 0  0  1  2  0  5  0  7  0 80]]


## DT Classifier
- training set: 6000
- test set: 1000

In [26]:
x_train = train_images[: 6000]
y_train = train_labels[: 6000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]
x_train = reshape(x_train)
x_test = reshape(x_test)

In [27]:
# fit data
DT = DecisionTreeClassifier()
DT.fit(x_train, y_train)
# predict
predict_y = DT.predict(x_test)

In [28]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.736
precision score:  0.7488753382028177
recall score:  0.7420363697250281
f1 score:  0.7434982630557865


In [29]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.72      0.64      0.68       107
           1       0.88      0.92      0.90       105
           2       0.57      0.65      0.61       111
           3       0.71      0.72      0.72        93
           4       0.68      0.55      0.61       115
           5       0.89      0.83      0.86        87
           6       0.39      0.46      0.42        97
           7       0.86      0.87      0.87        95
           8       0.91      0.84      0.87        95
           9       0.87      0.94      0.90        95

    accuracy                           0.74      1000
   macro avg       0.75      0.74      0.74      1000
weighted avg       0.74      0.74      0.74      1000



In [30]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[68  2  8  3  1  1 24  0  0  0]
 [ 1 97  0  5  0  1  1  0  0  0]
 [ 2  0 72  1 15  0 18  2  1  0]
 [ 6  6  2 67  2  0  9  0  0  1]
 [ 1  0 30  7 63  0 13  0  1  0]
 [ 0  1  1  1  1 72  0  7  1  3]
 [15  2 13  9  9  0 45  0  4  0]
 [ 0  0  0  0  0  2  0 83  1  9]
 [ 1  2  1  1  2  3  4  1 80  0]
 [ 0  0  0  0  0  2  1  3  0 89]]


## DT Classifier
- training set: 12000
- test set: 1000

In [31]:
x_train = train_images[: 12000]
y_train = train_labels[: 12000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]
x_train = reshape(x_train)
x_test = reshape(x_test)

In [32]:
# fit data
DT = DecisionTreeClassifier()
DT.fit(x_train, y_train)
# predict
predict_y = DT.predict(x_test)

In [33]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.768
precision score:  0.775462783233327
recall score:  0.7716259544249555
f1 score:  0.7723449614000295


In [34]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.77      0.73      0.75       107
           1       0.89      0.96      0.92       105
           2       0.63      0.71      0.67       111
           3       0.76      0.67      0.71        93
           4       0.68      0.62      0.65       115
           5       0.89      0.87      0.88        87
           6       0.54      0.59      0.56        97
           7       0.85      0.86      0.85        95
           8       0.90      0.83      0.86        95
           9       0.86      0.87      0.86        95

    accuracy                           0.77      1000
   macro avg       0.78      0.77      0.77      1000
weighted avg       0.77      0.77      0.77      1000



In [35]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[ 78   1   3   6   1   1  15   0   2   0]
 [  1 101   0   2   1   0   0   0   0   0]
 [  4   0  79   1  17   0  10   0   0   0]
 [  7  11   3  62   2   0   7   0   1   0]
 [  2   1  24   5  71   0  12   0   0   0]
 [  0   0   0   0   0  76   0   5   2   4]
 [  9   0  13   3  11   0  57   0   3   1]
 [  0   0   0   0   0   5   0  82   0   8]
 [  0   0   4   3   1   0   5   2  79   1]
 [  0   0   0   0   0   3   0   8   1  83]]


## SGD Classifier
- training set: 3000
- test set: 1000

In [36]:
x_train = train_images[: 3000]
y_train = train_labels[: 3000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]
x_train = reshape(x_train)
x_test = reshape(x_test)

In [37]:
# fit data
SGD = SGDClassifier(max_iter = 250)
SGD.fit(x_train, y_train)
# predict
predict_y = SGD.predict(x_test)

In [38]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.777
precision score:  0.7941135956757345
recall score:  0.7810455456193656
f1 score:  0.7820609433534768


In [39]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.92      0.61      0.73       107
           1       0.89      0.95      0.92       105
           2       0.58      0.80      0.67       111
           3       0.77      0.76      0.77        93
           4       0.69      0.62      0.65       115
           5       0.89      0.82      0.85        87
           6       0.53      0.54      0.53        97
           7       0.91      0.88      0.90        95
           8       0.86      0.93      0.89        95
           9       0.91      0.91      0.91        95

    accuracy                           0.78      1000
   macro avg       0.79      0.78      0.78      1000
weighted avg       0.79      0.78      0.78      1000



In [40]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[ 65   4  10   9   2   0  15   0   2   0]
 [  0 100   1   4   0   0   0   0   0   0]
 [  1   1  89   2   7   0  11   0   0   0]
 [  1   5   5  71   6   0   5   0   0   0]
 [  0   1  28   3  71   0  11   0   1   0]
 [  0   1   1   0   0  71   0   4   5   5]
 [  4   0  20   2  16   0  52   0   3   0]
 [  0   0   0   0   0   6   0  84   1   4]
 [  0   0   0   1   1   0   5   0  88   0]
 [  0   0   0   0   0   3   0   4   2  86]]


## SGD Classifier
- training set: 6000
- test set: 1000

In [41]:
x_train = train_images[: 6000]
y_train = train_labels[: 6000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]
x_train = reshape(x_train)
x_test = reshape(x_test)

In [42]:
# fit data
SGD = SGDClassifier(max_iter = 250)
SGD.fit(x_train, y_train)
# predict
predict_y = SGD.predict(x_test)

In [43]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.759
precision score:  0.8029436110222976
recall score:  0.7624172595010829
f1 score:  0.7606477463461297


In [44]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.63      0.87      0.73       107
           1       0.95      0.95      0.95       105
           2       0.49      0.88      0.63       111
           3       0.92      0.48      0.63        93
           4       0.80      0.38      0.52       115
           5       0.92      0.87      0.89        87
           6       0.54      0.46      0.50        97
           7       0.93      0.87      0.90        95
           8       0.93      0.89      0.91        95
           9       0.91      0.95      0.93        95

    accuracy                           0.76      1000
   macro avg       0.80      0.76      0.76      1000
weighted avg       0.80      0.76      0.75      1000



In [45]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[ 93   1   8   0   0   0   4   0   1   0]
 [  2 100   0   3   0   0   0   0   0   0]
 [  2   1  98   1   1   0   8   0   0   0]
 [ 24   3   7  45   4   0   9   0   1   0]
 [  5   0  54   0  44   0  12   0   0   0]
 [  0   0   3   0   0  76   1   3   1   3]
 [ 17   0  28   0   5   0  45   0   2   0]
 [  0   0   0   0   0   5   0  83   1   6]
 [  4   0   1   0   1   0   4   0  85   0]
 [  0   0   0   0   0   2   0   3   0  90]]


## SGD Classifier
- training set: 12000
- test set: 1000

In [46]:
x_train = train_images[: 12000]
y_train = train_labels[: 12000]
x_test = test_images[: 1000]
y_test = test_labels[: 1000]
x_train = reshape(x_train)
x_test = reshape(x_test)

In [47]:
# fit data
SGD = SGDClassifier(max_iter = 250)
SGD.fit(x_train, y_train)
# predict
predict_y = SGD.predict(x_test)

In [48]:
# report
accuracy = metrics.accuracy_score(y_test, predict_y)
precision = metrics.precision_score(y_test, predict_y, average = "macro")
recall = metrics.recall_score(y_test, predict_y, average = "macro")
f1 = metrics.f1_score(y_test, predict_y, average = "macro")
print("accuracy score: ", accuracy)
print("precision score: ", precision)
print("recall score: ", recall)
print("f1 score: ", f1)

accuracy score:  0.8
precision score:  0.8220317828922044
recall score:  0.8038901997993768
f1 score:  0.8090833470077957


In [49]:
report = metrics.classification_report(y_test, predict_y)
print(report)

              precision    recall  f1-score   support

           0       0.85      0.76      0.80       107
           1       0.94      0.96      0.95       105
           2       0.69      0.70      0.70       111
           3       0.76      0.77      0.77        93
           4       0.78      0.67      0.72       115
           5       0.93      0.85      0.89        87
           6       0.45      0.66      0.54        97
           7       0.92      0.93      0.92        95
           8       0.97      0.78      0.87        95
           9       0.93      0.96      0.94        95

    accuracy                           0.80      1000
   macro avg       0.82      0.80      0.81      1000
weighted avg       0.82      0.80      0.81      1000



In [50]:
confusion = metrics.confusion_matrix(y_test, predict_y)
print(confusion)

[[ 81   2   1   4   0   0  18   0   1   0]
 [  0 101   0   4   0   0   0   0   0   0]
 [  3   0  78   1   9   0  20   0   0   0]
 [  3   4   3  72   4   0   7   0   0   0]
 [  0   0  17   6  77   0  15   0   0   0]
 [  0   0   0   2   0  74   3   4   0   4]
 [  7   0  13   4   8   0  64   0   1   0]
 [  0   0   0   0   0   4   0  88   0   3]
 [  1   0   1   2   1   2  14   0  74   0]
 [  0   0   0   0   0   0   0   4   0  91]]


## Conclusion
- By comparing the experimental results in the paper, we can see that our accuracy is slightly lower. This is because in the SGD classifier, the max_iter we choose is 250, and the max_iter in the paper is 1000, so there is underfitting in our model.
- By comparing the three classifiers, KNN has the best classification effect, followed by SGD and DT.
- The increase of training set will increase the accuracy of the model slightly.